sudo: false
language: go
go:
  - tip
  - 1.7
  - 1.6
before_script:
  - go get -u github.com/golang/lint/golint
script: 
  - go get github.com/cloudflare/cfssl_trust/...
  - go test -cover github.com/cloudflare/cfssl_trust/...
  - go vet github.com/cloudflare/cfssl_trust/...
  - golint github.com/cloudflare/cfssl_trust/...
notifications:
  email:
    recipients:
      - kyle@cloudflare.com
      - zi@cloudflare.com
    on_success: change
    on_failure: change
