sudo: false
language: go
go:
  - tip
  - 1.5
script: 
  - go get golang.org/x/tools/cmd/vet
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/cloudflare/cfssl_trust/... 
  - go test -cover github.com/cloudflare/cfssl_trust/... 
  - go vet github.com/cloudflare/cfssl_trust/... 
notifications:
  email:
    recipients:
      - kyle@cloudflare.com
      - jacob@cloudflare.com
      - zi@cloudflare.com
    on_success: change
    on_failure: change
