sudo: false
language: go
go:
  - master
  - 1.13.x
env:
  - GOFLAGS=-mod=vendor GOPROXY=off
install: skip # explicitly disable the go get since we vendor deps
before_script:
  - go build ./vendor/golang.org/x/lint/golint
script:
  - ./test.sh

